image: "python:3.7"

before_script:
  - python --version
  - conda env create -f environment.yml
  - conda activate eodie

stages:
  - Static Analysis
  - Test

...

pytest:
  stage: Test
  script:
  - pytest