image: continuumio/miniconda3:latest

before_script:
  - conda env create -f environment.yml
  - source activate eodie
  - python --version

stages:
  - Test

pytest:
  stage: Test
  script:
  - pytest
