# Process only files with less than xx % cloudcover
maxcloudcover: 95

# Extract files with xx m spatial resolution 
# options: 10,20
resolution: 10

# Quantification value used to multiple the reflectance to get DN
# This could be read from metadata but for now at least is here
quantification_value: 10000