####

# Configuration file for the use of Sentinel-2 #

# Know what you do before you change anything here #

####

platform: 's2'

# Values to be to be included in cloudmask
# default [9,8,3,10,0,1]
tobemaskedlist: 
  - 9 # cloud high probability
  - 8 # cloud medium probability
  - 3 # cloud shadow
  - 10 # cirrus
  - 0 # no data
  - 1 # saturated and defective

# Sentinel-2 bands
red : 'B04'
green: 'B03'
blue: 'B02'
nir: 'B08'
r_edge: 'B05'
swir1: 'B11'
swir2: 'B12'

# some part of the products file name that identifies them as product to be used
productnameidentifier: 'S2*.SAFE'

# parts to build path towards bands
bandlocation: ['.','*','*','IMG_DATA']

# path building set after imgpath to get the bandfile
pathbuildinglist: ['R', 'pixelsize' , 'm','*', 'bandname', '_' , 'pixelsize' ,'m.jp2']

#indicator for cloudfile
cloudfilename: 'SCL'

tilepattern: '(?<=T)[0-9]{2}[A-Z]{3}'

#the first that is found is used
datepattern: '20[1-2][0-9][0-1][0-9][0-3][0-9]'

band_designation: 'B[0-1]?\dA?'

# Quantification value used to multiple the reflectance to get DN
# This could be read from metadata but for now at least is here
quantification_value: 10000

# available resolutions per band
B01: [60]
B02: [10,20,60]
B03: [10,20,60]
B04: [10,20,60]
B05: [20,60]
B06: [20,60]
B07: [20,60]
B08: [10]
B8A: [20,60]
B09: [60]
B11: [20,60]
B12: [20,60]
SCL: [20,60]
AOT: [10,20,60]
TCI: [10,20,60]
WVP: [10,20,60]



