name: eodie
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - shapely
  - rasterio
  - rasterstats
  - fiona
  - numpy
  - gdal
  - pyyaml
  - pytest
  - matplotlib
  - geopandas
