####

# Configuration file for adjusting the process/results and give paths #

####

# Process only files with less than xx % cloudcover
maxcloudcover: 99

# Extract files with xx m pixel size 
# options: 10,20 (for Sentinel-2)
pixelsize: 30

#resampling (converting to higher/lower resolution/smaller cells)
#available: 'biliner','nearest','cubic','average', ...
# from https://rasterio.readthedocs.io/en/latest/api/rasterio.enums.html#rasterio.enums.Resampling

resampling_method: 'bilinear'

#location of the shapefile with tiles (Sentinel2-tiles-world in case of Sentinel-2)
tileshp: ./shp_preparation/LS_tiles/WRS2_descending

#name of field where tilenames are stored in shapefile ('Name' in case of sentinel2_tiles_world)
fieldname: 'PR'